export default RoutineList = [
  {
    id: "up_1",
    title: "Fast Chest + Abs Workout",
    author: "Passion4Profession",
    tags: "Beginner",
    type: "Upper Body",
    desc: "Fast chest + abs Workout at home with trainer tips, no equipment required",
    videoID: "rlcBZ-YsG8A",
    calories: "100",
  },
  {
    id: "full_1",
    title: "7 Minute Fullbody Workout",
    author: "Passion4Profession",
    tags: "Beginner",
    type: "Full Body",
    desc: "A daily training to lose weight fast burn fat and tone your full body",
    videoID: "Uzo4DKvZEG4",
    calories: "100",
  },
  {
    id: "low_1",
    title: "8 Min At Home Leg Workout",
    author: "Chris Heria",
    tags: "Beginner",
    type: "Lower Body",
    desc: "Join Chris Heria as he shows you a 8 Min At Home Leg Workout You Can Do From Home. Learn How to Effectively build your legs with No Equipment and without weights.",
    videoID: "uLzLxV3TFqI",
    calories: "100",
  },
];
